spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/massage_project
#    username: postgres
#    password: pass

    url: jdbc:postgresql://localhost:5432/massage_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true

logging:
  level:
    root: TRACE
