spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/massage_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  messages:
    basename: messages

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      default_schema: massage

  mvc:
    format:
      date: iso

logging:
  level:
    root: INFO

app:
  image:
    bucket: Users/alexandria/IdeaProjects/dmdev-project/service/images;
